name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build, lint and test the frontend
  frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}

    - name: Test, lint and build
      working-directory: ${{env.working-directory}}
      run: |
        npm ci
        npm run all:ci

  # Build the backend
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}

    - name: Build backend
      run: |
        go get .
        go build patrick-hadlaw-server.go
